services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  auth-service:
    image: partyfinder/auth:latest
    container_name: auth
    ports:
      - "8721:8721"

  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    container_name: kafdrop
    depends_on:
      - kafka
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: kafka:9092
      JVM_OPTS: "-Xms32M -Xmx64M"

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    command: [ "redis-server", "--save", "60", "1", "--loglevel", "warning" ]


  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: artem
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: diploma
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

volumes:
  postgres_data:

  postgres:
    image: postgres:13-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: diploma
      POSTGRES_USER: artem
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data # Для сохранения данных между перезапусками

  app:
    image: your-spring-boot-app-image:latest # Замените на имя вашего Docker-образа
    container_name: app
    build:
      context: . # Указывает путь к Dockerfile, если вы собираете образ локально
      dockerfile: Dockerfile
    depends_on:
      - kafka
      - redis
      - postgres
    ports:
      - "8721:8721" # Порт вашего приложения
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/diploma
      SPRING_DATASOURCE_USERNAME: artem
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      TOKEN_JWT_SIGNING_KEY: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA53VzmIVVZZWyNm266l82
      TOKEN_JWT_DURATION_MINUTES: 20
      KAFKA_TOPICS_CREDENTIALS_CHANGES: credentials-changes

volumes:
  postgres_data: # Объем для хранения данных PostgreSQL