server:
  port: 8727

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/diploma
    username: artem
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.PostgreSQLDialect