server:
  port: 8723

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/diploma
    username: artem
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 100
          order_inserts: true
          order_updates: true



logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

scheduler:
  cron:
    rating:
      0 0 * * * ?
